<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ptcs-menu-submenu</name>
   <tag></tag>
   <elementGuidId>3a873285-8bdc-4350-8c72-b4cf4b02f132</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='runtime']/ptcs-menu-submenu</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ptcs-menu-submenu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ptcs-menu-submenu</value>
      <webElementGuid>a95cf055-2ebb-49c1-b0ec-415814246554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>popup</value>
      <webElementGuid>e0fcf2dc-414a-43f3-9a63-26e0665bae85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>bd28231f-7bab-4a99-9392-60bea0b3df45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>dark</value>
      <webElementGuid>50497a7d-8d0c-4cd7-a520-8d3fdc313a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a0904ea5-262c-4933-bbae-45ef9fa5c83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b307bb1f-bbb1-4bba-a6de-034211e95063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runtime&quot;)/ptcs-menu-submenu[1]</value>
      <webElementGuid>6bf03493-707d-4a7b-b70c-e6050f596101</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='runtime']/ptcs-menu-submenu</value>
      <webElementGuid>7953d76d-99c8-489d-82e9-19a1f0be8eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ptcs-menu-submenu</value>
      <webElementGuid>122d821d-becb-4a03-83f7-85a333d0cd5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
