<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xpath_Modular</name>
   <tag></tag>
   <elementGuidId>00b0ce78-d212-4c54-919c-43042d4d0904</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>${xpath}</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
