<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>thingworx-form-password</name>
   <tag></tag>
   <elementGuidId>115ac130-3018-4682-a2fc-88dea0c4b53f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;thingworx-form-password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='thingworx-form-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b404542-c503-44b2-80c8-953ae42b7be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field</value>
      <webElementGuid>f04a437e-8e31-426d-a610-d0a34a1ca68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>PASSWORD</value>
      <webElementGuid>8c7ce7e3-120a-4ae0-81c0-b881e2b26575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>thingworx-form-password</value>
      <webElementGuid>548ee59d-ddf9-46e8-819a-47fb11eebaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[placeholder]tw.login.labels.password</value>
      <webElementGuid>36619067-d87a-44ca-9c76-a81242756488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>2eac6474-61c6-40b5-9e2a-1de1c5ddcc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;login-container&quot;]/div[@class=&quot;login-form&quot;]/form[1]/input[@class=&quot;text-field&quot;]</value>
      <webElementGuid>f059565a-4679-4c83-bbad-6d366bf41f2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='thingworx-form-password']</value>
      <webElementGuid>d4e7b314-fec9-4740-a4db-ab8c3517e46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>9a0b87f9-ade0-4ce8-bbc4-0b6d5507aa8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'PASSWORD' and @name = 'thingworx-form-password' and @placeholder = 'Password']</value>
      <webElementGuid>1a11a2cd-a6b0-4193-8973-84ea8aa4b5c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
