<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>thingworx-form-userid</name>
   <tag></tag>
   <elementGuidId>b47921e3-cfc9-43b3-a3f3-5bb8704ba80a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;thingworx-form-userid&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='thingworx-form-userid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bae255ac-ec6e-4039-a8eb-c9eaba4b543e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field</value>
      <webElementGuid>93908770-84e5-4643-b72f-3b7fa57a4dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>64e1ceb1-7f5b-42ce-a619-55f284db1533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>thingworx-form-userid</value>
      <webElementGuid>6e9d33a4-4b99-47e8-9e53-252ecbdbf635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[placeholder]tw.login.labels.name</value>
      <webElementGuid>ee2168c3-962f-43bb-a57b-560e50ccb54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>95856bc2-23bd-4831-a4cd-ed21f0384057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;login-container&quot;]/div[@class=&quot;login-form&quot;]/form[1]/input[@class=&quot;text-field&quot;]</value>
      <webElementGuid>3e3d64c6-ba93-4d66-9357-da32a85ff822</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='thingworx-form-userid']</value>
      <webElementGuid>4297aa5f-d8f1-4767-bf01-1e8746464c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>951a05f4-1656-420c-b56f-1fbc0fed9a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'thingworx-form-userid' and @placeholder = 'Name']</value>
      <webElementGuid>8aa0e97f-ccd6-4be4-bda3-719d98666c47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
