<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lagging KPI2</name>
   <tag></tag>
   <elementGuidId>72e8195c-627c-41ec-b40f-f34c956c6523</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>L</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>IFRAME</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1572877844517</value>
   </webElementProperties>
</WebElementEntity>
