<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>id</name>
   <tag></tag>
   <elementGuidId>d08ccc4d-83b8-44b1-bdc6-857959a535c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>743ab923-d15b-46fd-9cc8-c35779684684</webElementGuid>
   </webElementProperties>
</WebElementEntity>
