<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ptcs-menubar_Show Log_root_ptcsmenubar-64</name>
   <tag></tag>
   <elementGuidId>1b266ff3-9aa1-4128-89be-a37c9fd42c76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ptcs-menubar[@id='root_ptcsmenubar-64']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root_ptcsmenubar-64</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ptcs-menubar</value>
      <webElementGuid>f236c2c7-e2c5-4cae-bef5-d4a66e4bbdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ptcs-wrapper widget-content widget-ptcsmenubar</value>
      <webElementGuid>0b000a81-ba52-4bb3-8bfd-62976b0527ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8c0bf7db-4a97-4c2c-b1a8-d70dd14da843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>root_ptcsmenubar-64</value>
      <webElementGuid>e741f148-b57e-4fee-843e-f68ead1f1457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root_ptcsmenubar-64&quot;)</value>
      <webElementGuid>be97a8aa-4fd5-4704-91e4-b39ca9e87b38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ptcs-menubar[@id='root_ptcsmenubar-64']</value>
      <webElementGuid>d1eac63a-082e-4c9a-ba36-f69e7729871b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root_ptcsmenubar-64-bounding-box']/ptcs-menubar</value>
      <webElementGuid>58d77fa9-d907-4d32-9637-a1c589d15856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ptcs-menubar</value>
      <webElementGuid>f57691d0-3811-4e4f-bc80-efb3b802adb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ptcs-menubar[@id = 'root_ptcsmenubar-64']</value>
      <webElementGuid>a18a2e3b-08e5-426f-aadb-1102733cc793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
