<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ptcs-menu-item--64-bb0-7b1</name>
   <tag></tag>
   <elementGuidId>704528cb-9a01-401b-9dd4-e85c39a98f0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='primaryitems']/ptcs-menu-item[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#navigatoritems > #primaryitems > ptcs-menu-item:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ptcs-menu-item</value>
      <webElementGuid>e7d388e0-5199-4981-b2f2-e363945feb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>dark</value>
      <webElementGuid>42140122-3cf6-4292-8867-bbd34d6d0803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>menu-item</value>
      <webElementGuid>9b2fc48a-9f2b-4754-bf63-06cc758897d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>level</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>909c20ef-aed0-4e86-ad27-45ed55013b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>348eb112-1e44-4636-ba01-9453bb1100b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Functions</value>
      <webElementGuid>cd6ed6e2-70fe-4b87-9cff-8bfffcbcea39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;navigatoritems&quot;]/div[@id=&quot;primaryitems&quot;]/ptcs-menu-item[2]</value>
      <webElementGuid>dea154dd-8339-4a89-9546-4d18629f952f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MouseOverTestForEHS/Page_Lupin DPM/ptcs-menu-flyoutflyout-ubar-64-bb0</value>
      <webElementGuid>c1beff70-b3f3-4d8f-89a6-6b8d8f4778bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>64fdb012-6679-4a9c-b04b-b8abc759278d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primaryitems']/ptcs-menu-item[2]</value>
      <webElementGuid>0b3ef270-fec7-4d43-9270-0b31ec9d12a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
