<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ptcs-icon-bb0-7b1-2c5</name>
   <tag></tag>
   <elementGuidId>f3c89af8-875a-4c5d-9458-229dcaff72d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ptcs-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ptcs-icon</value>
      <webElementGuid>46ec168d-3552-4828-94ff-daab7140dbb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>17d184cd-07b0-4068-93b6-61386e81c536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e7eb7e32-54b0-40c8-851e-2536af911c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>eff1edee-08f0-41ac-9615-32e10d73d0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/ptcs-icon[1]</value>
      <webElementGuid>5e260be8-f73d-445c-8b5c-75e2b39d06d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MouseOverTestForEHS/Page_Lupin DPM/ptcs-menu-item--64-bb0-7b1</value>
      <webElementGuid>5ed05cfd-4d9f-4f0f-891a-4718174d0ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ae02c31-33a2-4d90-bfbb-1278fc9534b7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
