<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ptcs-menu-flyoutflyout-ubar-64-bb0</name>
   <tag></tag>
   <elementGuidId>25916bbe-ffc1-4bea-9f9e-f0fb50fbfd97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='itemsarea']/ptcs-menu-flyout</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root > #mainarea > #itemsarea > #flyout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ptcs-menu-flyout</value>
      <webElementGuid>261d3ef4-d405-4044-86a7-b930477e9149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flyout</value>
      <webElementGuid>311f472a-4c97-407a-8874-9c28725c57e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>flyout</value>
      <webElementGuid>01d82f57-63d4-4946-bff5-cfcb8deb29d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>04e313e9-e26c-4ec1-83cd-bfb638928e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menubar</value>
      <webElementGuid>2ac674da-684d-492a-abe6-eaf0bc00d84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>c6e9d04e-6990-4d46-9d33-56eb28d3fb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;root&quot;]/div[@id=&quot;mainarea&quot;]/div[@id=&quot;itemsarea&quot;]/ptcs-menu-flyout[@id=&quot;flyout&quot;]</value>
      <webElementGuid>50890281-07cc-4890-b79d-aa9cb405dce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MouseOverTestForEHS/Page_Lupin DPM/ptcs-menubar_Show Log_root_ptcsmenubar-64</value>
      <webElementGuid>2bdf2f99-2655-4bea-90b2-72db48176f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9779ec15-a6a1-4060-9ee0-2fbbb59fb6d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='itemsarea']/ptcs-menu-flyout</value>
      <webElementGuid>1f7061da-ec8c-402b-af9b-7c1f1ca6dac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ptcs-menu-flyout[@id = 'flyout']</value>
      <webElementGuid>1aa6cf38-cae4-4d82-a5fd-dbf84d59cf4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
